name: IZA OS CI Pipeline
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
          
      - name: Run linting
        run: |
          pip install flake8 black isort
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check . || echo "Black formatting check failed"
          isort --check-only . || echo "Import sorting check failed"
          
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -f pyproject.toml ] || [ -d tests ]; then
            pip install pytest pytest-cov
            pytest --cov=. --cov-report=xml
          else
            echo "No tests found"
          fi
          
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run security scan
        run: |
          pip install safety bandit
          if [ -f requirements.txt ]; then
            safety check -r requirements.txt
          fi
          bandit -r . -f json || echo "Security scan completed with findings"
